version: "3.9"

services:
  price_api:
    image: docker.io/price_api:latest
    container_name: price_api
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - "--env-file=.env"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5000:80"
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload"
      ]
    restart: always
