version: "3.9"

services:
  price-api:
    image: docker.io/price_api:latest
    container_name: price_api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5000:80"
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload"
      ]
    restart: always
    depends_on:
      - db

  crawler:
    image: docker.io/crawler:latest
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: python runner.py
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 49153:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: always

volumes:
  postgres-data:
